### ISSUE TITLE
Change minimum width to 4

### ISSUE THREAD

**Issue by ildar** [WeAreFairphone/android_packages_apps_ClockWidget#2]
"edit" button stands too far on the right occupying the whole column. I guess moving it may allow to suit the widget into 4 columns

**Comment by jannispinter** [comment]
I think the main reason for this is the German translation of "edit". The German word is "bearbeiten" which is much longer than any other translation and thus needs more space on the screen.

Depending on the translation of the current day, the edit TextView might overlap with the current day TextView. I will look into this, maybe we can reduce the size of the widget somehow (or move the edit TextView somewhere else when the user reduces the size of the widget).

Furthermore, do you think that the "edit" label is actually appropriate for the function it serves? Maybe we can change it to something else (e.g. "alarms").

**Comment by paulkreuzer** [comment]
Could it be changed to a symbol (maybe an alarm clock with a +)?
Then it would take the same space in any language.

**Comment by Roboe** [comment]
The string size doesn't have any to do. How much rows/colums a widget takes up is calculated based on widget height and width (in `dp`). Best practices for widget sizing [are documented here](https://developer.android.com/guide/practices/ui_guidelines/widget_design#anatomy_determining_size) and recommends `250dp` size for maximizing the possibility of taking up 4 cells (columns, in this case).
