### ISSUE TITLE
Description on F-droid is misleading

### ISSUE THREAD

**Issue by snevas** [WeAreFairphone/android_packages_apps_ClockWidget#4]
https://f-droid.org/packages/com.fairphone.clock/

Please remove:
"You can cycle through the clock by tapping on it, and it will show different data, for example:

how long you own your Fairphone (this data is pulled from the motherboard manufacturer date)
until what time the battery will last
the amount of time you've had 'peace of mind' (based on Android's "no interruptions" setting)."

This is not included in the app: https://forum.fairphone.com/t/publishing-fairphone-specific-apps-launcher-contact-widget-on-f-droid/28008/45?u=snevas

**Comment by genodeftest** [comment]
This issue is better placed in F-droid's repository data issue tracker: https://gitlab.com/fdroid/fdroiddata/merge_requests/2947

By the way, the app is now moved to https://f-droid.org/packages/community.fairphone.clock/

**Comment by mueller-ma** [comment]
You could add the description to this repo and after that remove it from the fdroiddata repo. This way you don't have to wait for the fdroid maintainer and you can add screenshots and changelogs and the description can be translated.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-build-metadata-in-an-fdroiddata-collection

**Comment by Roboe** [comment]
I'll add the metadata to the repo, as @mueller-ma mentioned
