### ISSUE TITLE
Reduce widget height

### ISSUE THREAD

**Issue by genodeftest** [WeAreFairphone/android_packages_apps_ClockWidget#6]
Visually, the widget is just 2 rows high. On the home screen it takes 3 rows though, wasting one row of screen size. This may be caused by some vertical padding or margin.

I'd like to have the widget resizable to a height of 2 rows, reflecting its content height.

Version: 2.0 on F-Droid

**Comment by Roboe** [comment]
Rows are dynamic, in my experience, and it depends on screen size and launcher. It usually takes up 2 rows, sometimes it occupies 3 rows (like in the [Lawnchair](https://f-droid.org/packages/ch.deletescape.lawnchair.plah/) launcher).
Note that there's a space above the time which is non-empty when you have an alarm setted.

I'll investigate widget sizing.
